### ISSUE TITLE
Escaped unicode characters are not being recognized correctly by Espanso

### ISSUE THREAD

**Issue by TheChilliPL** [espanso/espanso#1007]
**Describe the bug**
I'm trying to insert the character `` (U+001B) using Espanso, but it does not work

**To Reproduce**
1. Add `` or `\u001B` into any replacement string in config
2. Try using it

**Expected behavior**
`` should be inserted

**Screenshots**
![image](https://user-images.githubusercontent.com/18823939/155862040-d62bbfe1-44b2-473d-8650-8b058633aa6b.png)
![image](https://user-images.githubusercontent.com/18823939/155862043-033e9356-7e2e-452c-a500-afcbfc5378ea.png)
![image](https://user-images.githubusercontent.com/18823939/155862046-211189a3-3f02-44eb-98ff-a1316eb600d5.png)

**Logs**
If possible, run `espanso log` in a terminal after the bug has occurred, then post the output here so that we can better diagnose the problem

**Setup information**
- OS: What OS are you using?: Win 11 22543.1000
- Version: which version of Espanso are you running? (you can find out by running `espanso --version` inside a terminal) Newest release

**Comment by mrjoecastellon** [comment]
If the replace value is supposed to output a "\", you need to type it double just like in the trigger.

**Comment by federico-terzi** [comment]
Hey @TheChilliPL,

Thanks for reporting this issue! I was able to reproduce the issue with `\u001B`, I'll investigate :)

That said, it's working correctly for me when I use `�` directly, did you write it like this?

```yaml
  - trigger: "char"
    replace: "�"
```

Cheers :)

**Comment by TheChilliPL** [comment]
Yes, that's what I tried before `\u001B`. Seems to work fine with the paste mode, though

**Comment by federico-terzi** [comment]
@TheChilliPL Thanks, interesting!

**Comment by brownjoel** [comment]
I can reproduce this issue on macOS 13.5 as well.  It seems to occur for any replacement string starting with \u001B, when in injection mode.  Interestingly, that character can be inserted if it is not the first character of the replacement string, just not if it's the start.

Switching to Clipboard mode works, but Clipboard mode has its own issues as I get occasional insertions of a lone 'v' instead of the replacement string.  Those insertions seem to happen more regularly if the computer is somewhat taxed, so it may be a timing issue, such as how long the Command key is held for the simulated paste.

**Comment by smeech** [comment]
I think `�` is simply an error replacement for the ESCAPE character U+001B and others in the range `\u0001` - `\u001f`, which aren't printable characters. Printable characters work fine from the codes. A different character for it appears in my editor on testing the triggers, but in other programs nothing appears at all. Pasting the character itself seems the best option.
