### ISSUE TITLE
YML parsing problem

### ISSUE THREAD

**Issue by soulllink** [espanso/espanso#1087]
So parsing error appears on line 10, symbol 14: " - q-mark.
Basically i'm interested into Latex snipet.
`
matches:
  - trigger: ":fr "
    replace: "\frac{$|$}{}"
    word: true
  - trigger: ":sys "
    replace: "\begin{cases}$|$\end{cases}"
    word: true
  - trigger: ":cd "
    replace: "\cdot"
    word: true
  - trigger: ":quad " #here line 10
    replace: "\[x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}\]"
    word: true
  - trigger: ":sq "
    replace: "\sqrt{x}"
    word: true
  - trigger: ":log "
    replace: "\log_{a}b"
    word: true
`

So, is there a general limitation with \Latex format?
[latexcelebi.txt](https://github.com/federico-terzi/espanso/files/8567287/latexcelebi.txt)
I renamed to txt to disable package.

**Comment by smeech** [comment]
The problem has arisen because of the quote marks around the replacements, which consequently require the backslashes to be individually escaped, in order to be returned.
```
  - trigger: ":fr "
    replace: \frac{$|$}{}
    word: true
  - trigger: ":sys "
    replace: \begin{cases}$|$\end{cases}
    word: true
  - trigger: ":cd "
    replace: \cdot
    word: true
  - trigger: ":quad "
    replace: \[x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}\]
    word: true
  - trigger: ":sq "
    replace: \sqrt{x}
    word: true
  - trigger: ":log "
    replace: \log_{a}b
    word: true
```
works fine, although the trailing spaces in the triggers _and_ the `word: true` properties mean that each one will need _two_ spaces to be typed after the text. This may or may not be what you want - I would keep `word: true` and dispense with the trailing spaces _and_ the quote marks around the triggers too.
