### ISSUE TITLE
Espanso does not work in alacritty when ctrl+shift+V is mapped to ^V (SYN)

### ISSUE THREAD

**Issue by NicolasWebDev** [espanso/espanso#1088]
**Describe the bug**
Espanso does not work in alacritty when ctrl+shift+V is mapped to ^V (SYN).
I am using that remapping because I want ctrl+v to map to Paste instead of ^V (see https://github.com/alacritty/alacritty/issues/3757#issuecomment-664381101).

**To Reproduce**
1. Remap ctrl+shift+V to ^V in Alacritty (`  - { key: V,               mods: Control|Shift,                   chars: "\x16"            }`)
2. Try to run a simple expansion
3. The trigger is deleted

**Expected behavior**
I would expect the expansion to work.

**Aditional info**
Just to make sure, I have disabled all of my other alacritty shortcuts.
Replacing the V key with another key (like G for example) makes espanso work fine in alacritty.
It used to work with Espanso v0.7.x.

**Logs**
Logs do not show anything.

**Setup information**
- OS: ArchLinux
- Version: espanso 2.1.5-beta
- alacritty: alacritty 0.10.1 (2844606d)

**Comment by AXGKl** [comment]
I had the same problem: 

My OS is Linux - on X11.

I mapped paste to `ctrl+v` because otherwise `ctrl+shift+v` is for block edit in vim:

```yaml
  - { key: V, mods: Control|Shift, action: ReceiveChar } # vim block edit
  - { key: V, mods: Control, action: Paste }
```

Then I checked this: https://espanso.org/docs/configuration/options/

and there it was promised that this

```
~/.conf/e/config ❯ cat alacritty.yml
filter_class: Alacritty
paste_shortcut: CTRL+V
```

would fix it. But it did not. I tried to configure other hotkey combos for paste in alacritty and configured like above - no success.

Well, the disclaimer said for `paste_shortcut`:

> Usually CTRL+V, but many built-in patches change this behavior

=> Suspicion: Those patches are *maybe* brutally ignoring user specific configs!? Would a bug, imho, but it it's true:  

I don't speak rust but I dared to pull the sources and saw that the `alacritty_terminal_x11.rs` patch really sets CTRL+SHIFT+V hard, w/o checking if overwritten in user config.

**Solution**:

1. Search in the sourced for alacritty and remove the alacritty patch.  
2. Recompile espanso: 

with app image:

```
 cargo make create-app-image --profile release
 mv target/linux/AppImage/out/Espanso-x86_64.AppImage /usr/local/bin/espanso
```

Now the hotkey overwrite in alacritty.yml is taken and all works :-)

**Comment by AXGKl** [comment]
Edit: Forget the recompile solution - you can simply declaratively tell espanso to ignore the internal patch and configure like so:

```yml
~/.config/espanso/config ❯ cat alacritty.yml
filter_class: Alacritty
paste_shortcut: CTRL+V
backend: Clipboard
apply_patch: false
```

**Comment by NicolasWebDev** [comment]
You sir, made my day. After nearly one year, I stumble upon your answer, and it indeed fixes my problem.

Thanks again @AXGKl .
