### ISSUE TITLE
Wayland Many Issues Not STarting Corrcectly Crashing and Turning on Caps Lock.

### ISSUE THREAD

**Issue by thorrrr** [espanso/espanso#1358]
HI 
Several issues not sure if you need to split the bugs but happens all the times.
On every boot-up Esp does not fully start shows a 5pc wide box on screen you have to click to get it to start correctly.
After start i use a few very simple triggers ;xx also tried ;vv  just to paste  a url every time it pastes url incorrectly freezes espanso and tuns on caps lock
Currently on Fedora 36 using Espanso 2.1.7-beta very difficult to use.

**Comment by ykill** [comment]
@thorrrr I have seen this tiny box in the center of my screen at boot-up.  When I press Escape, the box disappears and then I see the toast message stating that "Espanso has started correctly!"  At one time, I tried to resize this box, and was unable to read it.
openSUSE TW GNOME 42.4 Wayland (XWayland)
Espanso 2.1.7-beta built from source
Otherwise it is working correctly.

**Comment by smeech** [comment]
I'll close this issue as we have many documenting the additional window problem.
That having been said, the only Wayland distro I have tried is a Fedora 39 VM, where I compiled Espanso with only one glitch, and it doesn't exhibit the extra Window issue.
