### ISSUE TITLE
Espanso Replace ,ti to Japanese  word ち

### ISSUE THREAD

**Issue by UyCode** [espanso/espanso#1402]
**Describe the bug**
When I type anywhere with any English or Chinese Input Method, Espanso always replace the `,ti` to `ち`, and `,to` to `と` and so on, I search all the package I have and not found any triggers or regex for this problem. 

**To Reproduce**
1. any Input Method with Espanso enabled
2. type the world `,ti` anywhere you want.

**Expected behavior**
It should not replace to the Japanese word form.

**Screenshots**
![](https://github.com/UyCode/espanso-calc-new/blob/main/shots/Snipaste_2022-10-11_21-01-40.png)
![](https://github.com/UyCode/espanso-calc-new/blob/main/shots/Snipaste_2022-10-11_21-05-02.png)

**Logs**
no output logs

**Setup information**
- OS: Windows 11 Professional 64bit
- Version: 2.1.7-beta

**Comment by joh6nn** [comment]
I have no packages installed at all, and I can't reproduce this behavior, which suggests that it really is from a package that you have installed, and you just haven't found it yet, OR that it is caused by some other program and not espanso.

A quick way to check whether it is caused by an espanso package would be to temporarily close espanso, and see if the expansion still happens.

If it does indeed turn out to be an espanso package, the most effective way to find it would be to disable the packages 1 at a time and test the expansion. Whichever expansion you most recently disabled should be the one that has this expansion.

If you disable all packages and this behavior is still happening, then it would indeed be a bug in espanso, but as I noted, I personally can't recreate it.

**Comment by UyCode** [comment]
Thank you for your time, I do the process as you mentioned,  and I found this problem comes from the package called `vim-digraphs`. finally solved it,  thank you.

**Comment by UyCode** [comment]
it's caused by a package, thanks espanso team
