### ISSUE TITLE
Trigger with ctrl+u (ascii \X15) opens view-source in firefox

### ISSUE THREAD

**Issue by MikeVolk** [espanso/espanso#1447]
I have a trigger (mimicking MacOs behavior) of ctrl-u + (u, a, o) to create umlauts in windows. It simply looks like this in the base.yml file.

```
  - trigger: "\x15a"
    replace: "ä"
```

When I try the trigger in firefox, it opens the view-source page after ctrl-u, so the trigger can't get executed. 
I would expect the trigger to get intercepted so that I can type ä etc. 

Windows 11, espanso 2.1.6-beta

**Comment by smeech** [comment]
Sorry it's been so long since your post.
If I understand you correctly, you'd like Espanso to have priority over Firefox for a particular keystroke? This can probably be achieved by changing Firefox's settings, but I don't think that's something we should be trying to make Espanso do.
I'll close this for now but do get back to me, especially if I have misunderstood things!
