### ISSUE TITLE
Disable/enable option

### ISSUE THREAD

**Issue by koro-xx** [espanso/espanso#1525]
Hello, 
I'm a new user so perhaps I'm missing something, but this is what I see:

On Windows 10. I have noticed that using the option "enable: false" in default.yml makes the app completely useless. It starts fine and the taskbar icon shows up (and it shows as enabled), but no text expansion is done and the shortcut for the search bar does not work.
On the other hand if I remove that setting, the app starts enabled and works, and if I disable it by choosing the option in the taskbar menu, it does disable text expansion but keeps the search bar shortcut enabled (so I can paste snippets from there). This is precisely what I want by default, and the obvious setting "enable: false" seems broken (unless I misunderstood its meaning).

**Comment by jwigg-netscout** [comment]
I'm not a developer, but my understanding of that configuration option is that it's meant to be used in conjunction with application filters, so that you can disable Espanso completely in specific applications (eg, so that hotkeys and expansions don't interfere with a game or an app that has hotkeys that conflict with espanso, etc)

In the current release, I'm not sure there's a way for you to achieve what you're looking for via config options. However, I think that adding a startup task that runs `espanso cmd disable` will do what you want (it seemed to work in my testing on linux, I wasn't able to test on Windows)

**Comment by smeech** [comment]
I agree with @jwigg-netscout, `enable: false` is intended to be used to control programs via app-specific configurations. I'm interested in your workaround, @koro-xx, but I've also seen complaints in other Issues (#1142) that the Search Bar _shouldn't_ be popping up if Espanso is disabled!
