### ISSUE TITLE
Expanded text sometimes has typos

### ISSUE THREAD

**Issue by acorazza** [espanso/espanso#1668]
For example entering my trigger :email (which should type out my email address) often results in missing letters.

Logs show this: 

`[worker(2461)] [WARN] Received malformed char: data provided contains an interior nul byte at byte pos 0`

I'm using PopOS 22.04 (Ubuntu/Debian based)

**Comment by Brad-Habeeb** [comment]
could you provide the code you are using and espanso version. thanks

**Comment by acorazza** [comment]
Certainly. I'm using version 2.1.8. The code is:

```
 - trigger: ":em"
    replace: myemail@example.com

```

The issue is that sometimes a random letter is missing, i.e. "myeail@example.com" or "myemail@exmple.com"

**Comment by Brad-Habeeb** [comment]
Hi again, this is really a weird bug. however, I also got a similar issue when trying to insert a phone number or Email in some web forms because the designer set a limit on the number of characters to a specific number so when inserting an extra character to trigger a snippet it causes a missing character and it's usually the very last one. i.e. "abc@example.com" to be "abc@example.co" or sometimes remove the last one but keep the trigger attached to the Email address like this: ";abc@example.co".
here is my suggestion:

1. I noticed that you have some indentations and missing quotation issues in your code. it looks like you didn't copy it from the source file, just wrote it here quickly. Remember that espanso is written in Rust and it's a very sensitive language to indentations. here is the fix for your code:
` 
  - trigger: ":em"
     replace: "myemail@example.com"
`
2. open the terminal on macOS or CMD on WinOS and restart espanso by writing "espanso restart"
3. sometimes having a duplicated snippet can cause this issue. there is probably a bad match version for the same trigger.

**Comment by acorazza** [comment]
Indentations are OK but I was missing the quote marks around the email. I added them and tested a few times – it seems to work correctly now, so that must have been the cause. Thanks again for your help and for contributing to this excellent app!

**Comment by SNTag** [comment]
I'm having a similar problem on pop_os using x11 if anyone has any advice...

Snippets are frequently leaving the ":" after expanding or missing out on a letter. For example, when filling out applications, snippets to web links such as the below will leave out a letter and not lead to a valid address.

  - trigger: ":myli:"
    replace: "https://www.linkedin.com/in/myname/"

The errors seem repeated. Some example errors (created by espanso, I did not copy paste):

https://ww.linkedin.com/in/myname/   <----Missing w in www
:https://www.linkedin.com/in/myname/  <---- Added ":" in the front
https://ww.linkedi.com/in/myname/  <---- missing w in www and n in linkedin
https:/www.linkedin.com/in/myname/ <---- Missed a letter in myname and a / in https://

PS this seems like a great tool!

EDIT: I'm seeing this problem in other matches too now, should I open a new issue? even ":date" is having similar problems, missing a letter or leaving part of the match after expanding (ex, leaving ":").

EDIT 2: Figured out the issue! Added the following to espanso > config > default.yml:

key_delay: 5          # Ensure proper removal of trigger
inject_delay: 10    # Slows espanso down to ensure insertion of characters in right order
