### ISSUE TITLE
Libraries libwxbase and libwxgtk3 are deprecated in Debian 12 - unable to install the provided .deb file

### ISSUE THREAD

**Issue by sbstn87** [espanso/espanso#1674]
When trying to install the .deb packages on Debian 12 (stable) I get the error:

The following packages have unmet dependencies:
 espanso-wayland : Depends: libwxgtk3.0-gtk3-0v5 but it is not installable
                   Depends: libwxgtk3.0-gtk3-0v5 (>= 3.0.4+dfsg) but it is not installable
                   Depends: libwxbase3.0-0v5 (>= 3.0.4+dfsg) but it is not installable
E: Unable to correct problems, you have held broken packages.

There are newer version of those libraries installed in the system. It seems that dependencies in the package should be updated.

**Comment by zchap26** [comment]
Same situation over here:

I get an **identical error** trying to install **espanso-debian-wayland-amd64.deb** on **Debian 12 Bookworm**.

espanso is a most useful tool.

**Comment by eclipseo** [comment]
The package are called libwxbase3.2 and so on now on Bookworm, libwxbase3.0 is outdated.

**Comment by lutfiajib** [comment]
@amcdon03 
Following that link, i got alot of error while compile

Then this is the result:

$ espanso --version
espanso 2.1.8

$ espanso start
unable to start service: timed out
Hint: sometimes this happens because another Espanso process is left running for some reason.
      Please try running 'espanso restart' or manually killing all Espanso processes, then try agai_n.
      
 $espanso restart
espanso is not running!
unable to start service: timed out
Hint: sometimes this happens because another Espanso process is left running for some reason.
      Please try running 'espanso restart' or manually killing all Espanso processes, then try again.

and the last one:

$ ps ax|grep espanso
  35161 pts/4    S+     0:00 grep --color=auto espanso

Espanso still cannot running on Debian 12

**Comment by AucaCoyan** [comment]
Hi @sbstn87 ! I see that we have some information on the issue. Would you mind changing the title to something more related to the problem?
So we can search it easier when we have time to fix it! 🪂 
something like: libraries _a_ and _b_ deprecated in Debian _version_ should be allright
Cheers

**Comment by sbstn87** [comment]
Hi, 

I have changed the title.

By the way, there is already a pull request fixing the issue:
https://github.com/espanso/espanso/pull/1697

It has been open for almost 3 months, so I am starting to wonder, if perhaps this project is still maintained.

**Comment by AucaCoyan** [comment]
Thank you! Yes, I found the PR shortly after leaving my previous comment in this thread.
About maintaining the project, you are partially correct. In #1742 Federico said that he is short on time to dedicate to the project and [his contributions](https://github.com/espanso/espanso/graphs/contributors) surpass by far the 95% of the project.
This doesn't mean the project is stopped. I came by and ask for triaging issues permission and he allowed me to participate of the espanso org.
I'm slowly working a bit every day, but there is a huge amount of backlog to do. Currently I see more activity in the Discord (https://discord.gg/DFcCNDg7bB) than in reddit. If you want to help in some way, you are more than welcome!

**Comment by federico-terzi** [comment]
Hi folks! Sorry for the late reply, does anyone have an idea on how to address this comment? https://github.com/espanso/espanso/pull/1697#issuecomment-1826841180

I'm trying to figure out if we can produce a `deb` that is compatible with ubuntu <22 _and_ >=22, without requiring two different distribution pipelines

**Comment by ernstki** [comment]
For the benefit of those using Ubuntu 22.04 LTS (and derivatives):

The discussion in #1697 made it _seem_ as if the fix for this would still work with older Ubuntu/Debian releases lacking the newer wxPython libraries, but that doesn't appear to be the case as of [v2.3.0](https://github.com/espanso/espanso/releases/tag/v2.3.0), the latest Espanso release at the time I'm writing this.

Instead, you will need to [download 2.1.8](https://github.com/espanso/espanso/releases/tag/v2.1.8) from the releases page and use that instead (or compile from source), due to the unsatisfiable dependency on `libwxgtk` and `libwxbase` version 3.2. The Ubuntu Jammy repositories, for example, [only have 3.0](https://packages.ubuntu.com/search?keywords=libwxbase&searchon=names&suite=jammy&section=all).

**Edit**: Or use [the AppImage release](https://github.com/espanso/espanso/releases). `:)`

**Comment by smeech** [comment]
Or use the AppImage?
