### ISSUE TITLE
Can trigger support Chinese symbols? Can you add a hotkey to the way you trigger the replacement of text?

### ISSUE THREAD

**Issue by LDzzZ-1** [espanso/espanso#1693]
**first problem**
such as
```yaml
  - trigger: "，，"
   replace: ","
 - trigger: "【【，"
   replace: "[|]"
```

ok One solution to the first problem that comes to mind is reversal, but a few problems arise

```yaml
  - trigger: ".."
   replace: "。"
```
However, it is not possible to enter multiple consecutive punctuation(.)

Based on my previous experience with an Obsidian plugin, I came up with a **second problem**
trigger+hotkey replacement of text  
such as 
When I type punctuation(**.**), press **backspace** ,and replace the punctuation with 。

But I'm too knowledgeable about code, so I can only make a suggestion
Also attached is the address of that plugin
I hope it helps you.
[easy-typing-obsidian](https://github.com/Yaozhuwa/easy-typing-obsidian)

**Comment by AucaCoyan** [comment]
The problem lies in:

>  When I type punctuation(.), press backspace ,and replace the punctuation with 。

Backspace is a special character, when you press it espanso actually "deletes" the last char from the monitor, so how can we detect different a backspaces when you are actually wanting to delete a char o to complete the trigger?
It's better to use a different trigger, for example `..;`
