### ISSUE TITLE
Want to become an Espanso maintainer? :)

### ISSUE THREAD

**Issue by federico-terzi** [espanso/espanso#1742]
Hi everyone!

As many of you have noticed, my contributions to the project have slowed down significantly in the past year, and I'm really sorry about that. The reason is that I've taken on many commitments both in my professional and personal life, and that limited the amount of bandwidth I could dedicate to Espanso.

The good news is that the Espanso community is still growing, and I want to make sure the project has a bright future ahead. For this reason, I'm asking the community: is there someone willing to join the Espanso maintainers team? (which at the moment, it's just me :D ). 

The activity would involve following:
- Helping people on GitHub and Reddit
- triaging issues
- Reviewing PRs and packages on the Hub
- Contributing to the codebase
- Improving the documentation
- Helping the Espanso community foster in general

Note: you could also just help on a specific area :) For example, if you are not comfortable with coding but would like triaging issues, that would already be a great help!

Note #2: I'm not abandoning the project :) I'll still be there if a critical issue comes up, and I don't exclude the possibility of actively contributing again in the future if my life circumstances allow it

If you are interested, please reach out to me :) https://federicoterzi.com/contact-me

Happy expanding!

**Comment by mistahBen** [comment]
I have virtually no experience with rust but Espanso is a utility that I find almost endlessly useful. Would love to try and help in some way(s), in particular documentation/triage.

I've spent most of my time-in regards to Espanso- trying to answer questions over on Reddit. (Username `30ghosts`)

**Comment by joh6nn** [comment]
I would be glad to triage Github issues and help people here when I'm able. I can also help with documentation, testing, and reviewing packages on the hub.

I don't have much rust experience, but I'm interested in learning and would be glad to contribute code and review PRs as I'm able to.

**Comment by federico-terzi** [comment]
Thank you folks! I appreciate the help :) Are you comfortable in coding other languages? I'm asking because one easy place to get started could be the [Espanso Hub](https://github.com/espanso/hub). We have many packages waiting for review, and while there's some basic CI pipeline to validate them, we could do a lot better in terms of automation :) Let me know if you're interested

**Comment by joh6nn** [comment]
Yep, I'm comfortable with several other languages, just not rust :slightly_smiling_face: Reviewing PRs on the hub is something I can do; I've written some private packages for use at work

**Comment by anshulxyz** [comment]
I'd like to get involved in the project. I have a tiny experience in fixing issues in open source Rust project.

Been using Espanso for a year now. And I love the project. Would like to contribute by fixing bugs.

**Comment by federico-terzi** [comment]
Thank you folks!

I'm thinking of creating a dedicated maintainers channel on the Espanso Discord server so that we can have a more direct means of communication :) Feel free to join if interested, mentioning that you'd be interested in helping out :) https://discord.gg/DFcCNDg7bB

> Edit: one thing I can do is adding tags to issues. In the other project I'm working on, [nushell](https://github.com/nushell/nushell/issues) have a lot of issues and most of them tagged with multiple options, so it's easy to focus on a topic.
> What do you think? Can you do a profile that only can add tags to issues? I'd be great!

@AucaCoyan That would be great! What do you mean with "Can you do a profile that only can add tags to issues?"? Do you mean creating a new GitHub account? :)

> I like Rust. I love the project. Would like to contribute by fixing bugs. Let me know how I can help.

@anshulxyz That's great! I'd suggest joining the Discord server, so that in the upcoming days we can gather ideas and decide the next steps :)

**Comment by AucaCoyan** [comment]
> What do you mean with "Can you do a profile that only can add tags to issues?"? Do you mean creating a new GitHub account? :)

No, I believe you as an admin of the organization you can "create profiles", much alike role permissions in a Discord. So not every maintainer can do everything in a security aspect (I never did that, so sorry if I'm mistaken!).

In [this page](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#repository-roles-for-organizations) says that you can select different roles for different contributors. My guess is that it's available for free open source projects and you don't need some kind of enterprise subscription.

Looking forward to the results! 🙌🏼

**Comment by devcrafting** [comment]
Hi @federico-terzi, probably not a main maintainer (first I am not fluent in Rust), but I was [thinking to help on an issue I logged today](https://github.com/espanso/espanso/issues/1760), but I am a bit lots how to start developping/debugging. [I saw this file](https://github.com/espanso/espanso/blob/dev/Compilation.md), but seems incomplete and I am a bit lost since not used to Rust dev env. Typically, I thought I could build a version not to publish just to test (the new version of markdown crate) ? Also, I do not know how to run existing tests ? Could you elaborate a bit more this page + add a link in the main Readme with a short section "Contribute" with link to this page and to this issue ?

**Comment by AucaCoyan** [comment]
Hi @devcrafting Clément! don't worry about the fluency of Rust. I think many people get good at any language just by contributing to open source and putting hands to work!
I can link you to [our discord](https://discord.gg/DFcCNDg7bB) so we can chat.
See you around!

**Comment by devcrafting** [comment]
I am on Discord @AucaCoyan now. I now it is "quite easy" to get started on new language (I am also used to functional programming with F#), but still not sure have this time to do more that fixing some issues very occasionally (I do not develop much in my own company because missing time...).

BTW : I tried on my own to build and run on Linux and Mac, it is quite easy (cargo make is great and Rust compiler really explicit when missing something). I can try to elaborate a bit the Compile page if you want ?

**Comment by AucaCoyan** [comment]
Yes please! I'm having troubles with the compilation in windows  😄

**Comment by devcrafting** [comment]
Oups I tried on Linux and MacOs, not yet on Windows :smile:

**Comment by reitzig** [comment]
I nominate @dependabot for a more active role. 😬

Honestly, though: My main concern with espanso is that it's effectively a keylogger, so I'd love to be able to trust that it's  kept up to date with any security updates in its dependencies at least.

I can not commit any capacity myself, unfortunately. Will nudge bored Rusters in my bubble, though. 😀

**Comment by DylanLacey** [comment]
Happy to help! I've not done any rust but can probably pick it up. 

I'm also willing to help with Espanso Hub; what kind of support are you looking for there?

**Comment by Mte90** [comment]
> I'm also willing to help with Espanso Hub; what kind of support are you looking for there?

I think that the issue on the hub is the queue to get an approval for a new version of a package and maybe something more fast and simple to manage those package updates for package owners.

**Comment by federico-terzi** [comment]
Regarding the Hub, we'll start an effort to improve the process soon :)

The reason why the reviews on the Hub have been so slow in the past few months is that I wanted to personally review every package/update that is published on the hub, and I've been at capacity lately. My original motivations:
* Nothing stops a package maintainer from publishing a good looking package, and then publishing an update that contains a match like:

```yaml
  - trigger: "a"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "rm -Rf ~"
```

so that as soon as the user types `a`, all their files are gone. Script and shell extensions are particularly dangerous.

* Users can install packages from outside the Hub as well, if they don't want to wait for a review: https://espanso.org/docs/packages/external-packages/

On one hand, I'm against walled gardens (like Apple's AppStore), but on the other, I'd love to maintain the user expectation that every package they download from the Hub is vetted and safe. There are approaches to mitigate the effort (like improving automatic checks), but removing the review process (even for known package creators) could lead to dangerous packages being released. Keeping in mind that users can still share their packages with others outside the Hub, I still believe that this model is better (although scaling the reviewers team is for sure necessary, because I'm definitely a bottleneck here)

Thoughts?

**Comment by reitzig** [comment]
Seems to me you just gave excellent reasons for excluding script and shell extensions from the hub, on principle.

Would the remaining set of packages be easier to handle?

**Comment by Mte90** [comment]
Maybe create a CI that validates the packages?
I mean if there are commands there is an alert in the PR so the maintainer can check them.

Because I publish packages with `yml` files with over 7000 or 20000 lines...

**Comment by AucaCoyan** [comment]
> Maybe create a CI that validates the packages?

Yes that sound reasonable. I'll submit an issue!

**Comment by joh6nn** [comment]
> On one hand, I'm against walled gardens (like Apple's AppStore), but on the other, I'd love to maintain the user expectation that every package they download from the Hub is vetted and safe.

This is part of a larger package moderation discussion that will need to happen. It deserves its own Issue or Discussion, but in brief, packages can potentially contain:

- hate speech
- adult/objectionable/illegal material
- ads
- political speech
- content that no one on the official moderation team is able to vet (language none of them speaks, etc.)

And unfortunately, none of those are things that can be dealt with via automation, and they are also potentially subjective. (is this opinion or hate speech? is it art or pornography? is this legal in your country but not mine?) 

I have thoughts on how that can potentially be dealt with, if we decided as a community we want to take responsibility for that, but again, this likely deserves discussion in its own issue

**Comment by AucaCoyan** [comment]
That is so right on the point @joh6nn !

**Comment by reitzig** [comment]
Reality check: How does Maven Central do it? Or PyPi? Or Rubygems? Or sdkman? Or GitHub Packages?

As far as I know, _none_ of those, definitely not all, vet deliverables pushed to their systems. Maybe there are flagging features so offensive/dangerous content can be taken down once identified by the community. (For which there seems to be a high bar: to this day, you can pull [log4j 2.14](https://en.wikipedia.org/wiki/Log4Shell) off Maven Central!) Otherwise, responsibility for their systems' integrity rests firmly with the users.

Okay, I'm thinking of developers as target group. If espanso wants to target less technically proficient groups, different trade-offs will have to be made. (And it starts with: Beware, user, as you are about to install basically a keylogger!)

(What this means is that `espanso install` should maybe give us a way to review what we've just installed before _activating_ is, but that's a whole different discussion.)

**Comment by Mte90** [comment]
Maybe it's better to move the discussion about packages in another ticket?

**Comment by federico-terzi** [comment]
Hey folks :) Thanks for all the input, let's continue the discussion here: https://github.com/espanso/hub/issues/98

**Comment by AucaCoyan** [comment]
We had discussed a lot about the topic. Luckily a new team was formed and the community adapted all the repositories: website, hub, hub-frontend and of course espanso repos).
I'm closing this issue just because is "solved" in the way it was proposed (looking for a maintainer). 
If you are reading this and want to contribute, feel free to come and ask anything! We welcome people from all the world and all level of experience! For example we have a couple that don't know a thing about how to code, or people who never wrote `hello world` in rust making simple contributions to the espanso core. 
Show us your superpowers! 🚀 ✨

**Comment by rayvermey** [comment]
Yes if i can help reach out to me. Espanso is such a wonderful great tool!

**Comment by smeech** [comment]
> Yes if i can help reach out to me. Espanso is such a wonderful great tool!

Welcome! Come and join us and say hi on the [Discord](https://discord.gg/4QARseMS6k) server!
