### ISSUE TITLE
Add notification at startup to notify if a new update is available

### ISSUE THREAD

**Issue by federico-terzi** [espanso/espanso#382]
Of course, this feature can be disabled with the option:

```
check_updates: false
```

**Comment by andylima** [comment]
Adding this feature doesn't make much sense, IMO:
1. Because many users leave their laptop running for weeks (putting it on sleep mode at the end of the day), so espanso would only show that "new version" message, say, after weeks had passed.
2. Users already have **a feature better than that: just toggle `Watch → Custom → Releases`** right here on the GitHub repo. And you'll be notified by email **immediately when an update is released**. Instead of after days/weeks when you eventually restart your computer and espanso.

**Comment by federico-terzi** [comment]
@andylima Good point, thank you! This is by far one of the lowest priority issues, so unlikely it will be implemented soon anyway :)
