### ISSUE TITLE
Replacements aren't working in Microsoft RDP

### ISSUE THREAD

**Issue by DarrellTang** [espanso/espanso#463]
I'm using espanso and trying to do replacements over an RDP connection on Mac OS but it's not working. It actually seems to be very similar to this issue here: https://github.com/federico-terzi/espanso/issues/128

When i try to execute a replacement, it deletes the trigger text and seems to enter a series of spaces rather than the replacement text. 

I've tried both Inject and Clipboard backends, same behavior. 

Any ideas on what I can try? What information would help to troubleshoot this?

**Comment by federico-terzi** [comment]
Hey @DarrellTang,
Unfortunately, RDP is known to be a bit problematic with espanso (as far as I remember). What OS is the Host using? Are you connecting to a macOS machine from a Windows on or vice-versa?
Cheers :)

**Comment by DarrellTang** [comment]
I'm connecting to a windows server 2k12 r2 instance over rdp from my newly
provided work MacBook pro.

**Comment by federico-terzi** [comment]
@DarrellTang I see, thank you. I'll investigate

**Comment by DarrellTang** [comment]
Thank you! Please let me know if there's any info I can provide to help!

Darrell

**Comment by DarrellTang** [comment]
Hello, is there any way I can help with testing?

**Comment by federico-terzi** [comment]
@DarrellTang Thank you Darrell, unfortunately, I still haven't got the chance to properly investigate this issue. I'll make sure to let you know once there is something ready to try out!

**Comment by AucaCoyan** [comment]
Remote Desktop is something that is outside of scope 😢 . We couldn't do it until today!

**Comment by phorcys420** [comment]
For the record, I use espanso with RDP software and I'm fine.

I initally ran into some issue but I settled on the following app-specific config and it's been working properly since then.
```yaml
filter_exec: mstsc.exe

backend: Inject
key_delay: 2
```

Obviously this one is only for Windows' built in client but you should be able to change the executable depending on your platform/RDP client.

I am using the `Inject` backend because not all RDP hosts support the clipboard and the `Clipboard` backend (default) used to output scrambled text in remote connections.
The `key_delay` is set to `2` instead of the default which is `1` to avoid scrambled text with slower RDP connections.

You can't use espanso with mstsc in fullscreen because it uses a kernel level way of reading your keystrokes which can't be read by software like espanso (probably to avoid from keylogging) without a custom kernel module.

**Comment by ITistheworst** [comment]
I was having this exact same issue in Microsoft's 'Windows App' RDP app with MacOS, the trigger gets cleared out but nothing replaces it. The fix that worked for me was to open the RDP connection and then in the menu bar go to `Connections` -> `Keyboard Mode` and switch it to `Unicode` instead of `Sancode` (or press `⌃⌘ U`).

The insertions now work for either `inject` or `clipboard` modes, however I have always found the clipboard handling by the Windows App to be pretty flaky so I have forced to always inject for that app by creating `windowsApp.yml` in the config folder:

```yaml
filter_exec: "Windows App"
backend: inject
```
