### ISSUE TITLE
non-letter character in trigger and "word: true"; special keys

### ISSUE THREAD

**Issue by tmsg-gh** [espanso/espanso#502]
Hi Federico,

nice project. Ever since I switched to Linux, I've wished for a reliable text expansion utility. I did something with AutoKey but this has never been as reliable as AutoHotkey was under Windows. So it's great to see your project... and first tests have been very promising.

I have two suggestions. (I've looked through back issues WRT these and found nothing but if they have already been discussed just close this.) Here goes:

1. I have a long list (150+) of simple static expansions, many of which I've used for ages even under Windows. These are all triggered by a short string (1 to 3 characters) and a terminating backtick\grave (\`). This works very well. However... there's one small problem. Some of the triggers are single characters or common two character combos (say "he\`"). When I now type "The\` " the "he\`" part gets expanded. No problem, I simply add "word: true" to the definition. Alas, now the expansion doesn't work anymore. Can you adapt the word feature so that it also works if there are non-letter characters in the trigger?

2. Leaving simple static expansions, I have many expansions which require injecting (ie they would not work via the clipboard) left, right, up, down arrow, home, end etc. Any chance these will be supported in a future version? I've seen #286 but this going even further.

Thanks for listening and many thanks for espanso!

**Comment by federico-terzi** [comment]
Hey @tmsg-gh,

Thanks for reporting this issue! I never thought about the possibility of using the `word` option with special characters, so no surprise it's not working as expected. I'll investigate and see whether that could be fixed in a reasonably easy way

> Leaving simple static expansions, I have many expansions which require injecting (ie they would not work via the clipboard) left, right, up, down arrow, home, end etc. Any chance these will be supported in a future version? I've seen #286 but this going even further.

I definitely plan to add those, but it will take some time (a few months) as it requires a good deal of thinking from my side. So if you are interested, activate notifications on that issue.

Cheers :)

**Comment by tmsg-gh** [comment]
Thanks for looking into that.
> I'll investigate and see whether that could be fixed in a reasonably easy way

That would be great as I am using this style (with backticks) and these expansions literally since decades :smile: 

While I'm at it... do you think it's possible/worthwhile to add special character combinations (like Ctrl+Alt+X etc) not only in expansions but also as triggers? This would enable me to get rid of AutoKey altogether.

Last but not least, I've noted that the espanso executable is around 11MB in size. I know that Rust normally compiles statically linked programs... but 11MB seems somewhat excessive either way. How come?

**Comment by federico-terzi** [comment]
Hey,

> While I'm at it... do you think it's possible/worthwhile to add special character combinations (like Ctrl+Alt+X etc) not only in expansions but also as triggers? This would enable me to get rid of AutoKey altogether.

There is already an issue about that #383. I guess it will eventually make it's way into espanso (as I'm planning to add shortcuts support for another feature), but probably this will take some time as well...

> Last but not least, I've noted that the espanso executable is around 11MB in size. I know that Rust normally compiles statically linked programs... but 11MB seems somewhat excessive either way. How come?

Running [cargo-bloat](https://github.com/RazrFalcon/cargo-bloat) gives the following output:

```
File  .text     Size Crate
 8.0%  20.1% 910.2KiB std
 5.2%  13.1% 593.4KiB reqwest
 3.0%   7.6% 343.3KiB clap
 2.2%   5.6% 252.1KiB regex
 2.1%   5.2% 237.4KiB regex_syntax
 1.9%   4.9% 221.0KiB espanso
 1.4%   3.6% 161.1KiB h2
 1.4%   3.5% 157.0KiB unicode_normalization
 1.3%   3.3% 149.4KiB serde_yaml
 1.0%   2.5% 114.9KiB hyper
 1.0%   2.5% 112.4KiB notify
 0.8%   2.1%  95.2KiB yaml_rust
 0.7%   1.7%  78.2KiB [Unknown]
 0.6%   1.6%  72.9KiB serde_json
 0.6%   1.6%  72.6KiB aho_corasick
 0.6%   1.4%  65.5KiB idna
 0.5%   1.4%  62.1KiB term
 0.5%   1.3%  59.8KiB http
 0.5%   1.2%  52.2KiB markdown
 0.4%   1.1%  49.8KiB url
 5.0%  12.7% 574.6KiB And 82 more crates. Use -n N to show more.
39.8% 100.0%   4.4MiB .text section size, the file size is 11.1MiB
```

So it seems to be mostly due to the Rust std, reqwest (used to install espanso packages), clap to parse command line args and a good portion ~40% to symbols (which as far as I know could be stripped away, but are very useful if the program panics and we look at the stack trace). Feel free to experiment with `cargo-bloat` if you want to analyze this further.

Honestly, I never thought about investing time to reduce the final size as I always considered everything below 20mb barely noticeable on modern systems. But thanks for pointing that out, I'll keep an eye on it to make sure it doesn't grow too much in future versions :)

**Comment by tmsg-gh** [comment]
> I always considered everything below 20mb barely noticeable on modern systems.

Well, I am showing my age here :smile: I remember disassembling parts of something called Turbo Pascal around 1982 
(when I was still very young and perhaps somewhat handsome). This was a 34KB executable (if memory serves) and it contained a) a recursive descent Pascal compiler, b) a basic runtime library and c) a simple IDE and editor.  I don't think I've ever seen anything like it.

As to espanso, good old strip already reduced file size from ~11MB to around 8.5MB. I was just wondering how that pans out. Never mind.

Keep up the good work!

**Comment by federico-terzi** [comment]
> Well, I am showing my age here 😄 I remember disassembling parts of something called Turbo Pascal around 1982
(when I was still very young and perhaps somewhat handsome). This was a 34KB executable (if memory serves) and it contained a) a recursive descent Pascal compiler, b) a basic runtime library and c) a simple IDE and editor. I don't think I've ever seen anything like it.

Those days must have been a combination of great fun and frustration :)

Thanks for the useful insights!

**Comment by smeech** [comment]
I think we can close this. Short triggers suffixed with "`" seem to work reliably now. Espanso can utilise [CTRL characters](https://espanso.org/docs/matches/basics/#keyboard-triggers) with ASCII codes as triggers and replaces, but not ALT-, or META- etc. without a significant rewrite.
