### ISSUE TITLE
Google docs support

### ISSUE THREAD

**Issue by shoryamalani** [espanso/espanso#555]
When you go to google docs and type in an expansion only the first letter comes up.
Considering the popularity of google docs I apologize if this is a repeat but i could not find the issue.

**Comment by federico-terzi** [comment]
Hey @shoryamalani,

I'm sorry you experienced this problem! Could you please try to add this line on your `default.yml` file and see if that helps?

```yaml
backend: Clipboard
```

Cheers :)

**Comment by shoryamalani** [comment]
So I added that to the file using espanso edit and then did espanso restart. Espanso now works in google docs in firefox but not safari, Thank you for the quick reply.

**Comment by federico-terzi** [comment]
@shoryamalani That's interesting! Thanks for reporting, I'll investigate and get back to you once I find something :)

**Comment by andreionut** [comment]
Works well in Safari on macOS Big Sur 11.2.3

**Comment by smeech** [comment]
Most of these problems can be resolved by changing the `backend:` globally or via `force_mode:` for individual triggers, with app-specific configurations where necessary. If this is still a problem, have these been fully explored?
Happy to reopen if necessary.

**Comment by vctls** [comment]
Still having issues in Google Docs, in Firefox specifically: replacement work, more or less (sometimes the initial character is not replaced), but the tab completely freezes for two or three seconds before the replacement is printed.
Using Firefox 134.0b2 on Ubuntu 22.04, X11
I've already tried different combinations of these two options:
```
disable_x11_fast_inject: true
backend: Clipboard
```
AutoKey works fine in this context (but not in others, like Kitty terminal).
No issues in Chromium.
No issues on other sites in Firefox either.

**Comment by smeech** [comment]
I'm happy to try and help. In Google Docs in Brave, my various triggers work as reliably as they do elsewhere. Firefox is, as you say, less reliable, but works better with the `clipboard` backend rather than my usual `auto`.

I'll attach my current configuration output of `#acfg#` for Firefox. Unfortunately, GitHub won't allow a YAML file upload, so you may wish to rename it to benefit from syntax highlighting,

The main setting which removes the delay you're seeing appears to be `x11_use_xclip_backend: true` which I use globally in my `config/default.yml` (you may need to install `xclip` to try it), but there may be other differences.

Linux Mint Linux Mint 21.2 x86_64, Xfce, Firefox 132.0.1
[firefox_acfg.txt](https://github.com/user-attachments/files/17960960/firefox_acfg.txt)

**Comment by vctls** [comment]
@smeech `x11_use_xclip_backend: true` did the trick, thank you!

**Comment by smeech** [comment]
You're welcome - thank you for letting me know.
