### ISSUE TITLE
bad trigger on "italian-accented-words" package

### ISSUE THREAD

**Issue by marco-acorte** [espanso/espanso#614]
I have found a bad trigger on "italian-accented-words" package

![immagine](https://user-images.githubusercontent.com/6375935/110480828-36325100-80e7-11eb-8477-602142dfdd93.png)

this trigger will affect every single isolated "e" converting in "è" 

adding a comment in ..\espanso\packages\italian-accented-words\package.yml will fix this issue.

**Comment by marco-acorte** [comment]
I don't know if this repo is the right place where to open an issue for a package in espanso hub... :-)

**Comment by federico-terzi** [comment]
Hey Marco,

Thanks for reporting this issue! I'll make sure to fix it as soon as I get my hands on the Hub :)

In a few months, we will refactor the package system so that users can directly contribute to the packages through pull requests. Hopefully, this will make things easier the next time something like this happens :)
