### ISSUE TITLE
Injection Mode not working in PowerShell on Windows 10

### ISSUE THREAD

**Issue by JamesDBartlett3** [espanso/espanso#630]
Affected applications: 

* Windows PowerShell 5.1
* PowerShell Core 7.1.3

Affected OS: 

* Windows 10

Problem description: 

* When using Injection mode, if I type a trigger into one of the affected applications, Espanso deletes the trigger, but then fails to type the trigger's replacement text value.
* Trigger replacement works as expected in the affected applications when using Clipboard mode, but that also clutters up my clipboard history, so I'd really prefer to use Injection mode if possible.

**Comment by federico-terzi** [comment]
Hey @JamesDBartlett,

Thank you for reporting! I can't give you any ETA on this, but we should be able to solve it. As soon as I have some time, I'll investigate :)

Cheers :)

**Comment by federico-terzi** [comment]
For my future self, this issue is likely caused by the `KEYEVENTF_UNICODE` flag not being recognized in the terminal (see 
https://github.com/federico-terzi/espanso/blob/master/native/libwinbridge/bridge.cpp#L509 )

To solve this problem we will need to introduce an alternative mode based on a keycode mapping table, as done on X11.

**Comment by JamesDBartlett** [comment]
> To solve this problem we will need to introduce an alternative mode based on a keycode mapping table, **as done on X11**.

Purely out of curiosity, is this related to the "Auto" injection mode, which[ the docs say](https://espanso.org/docs/configuration/#options) is "Linux only"?

**Comment by federico-terzi** [comment]
> Purely out of curiosity, is this related to the "Auto" injection mode, which the docs say is "Linux only"?

Unfortunately, it's a completely unrelated thing. 
Basically, on Windows and macOS we have a way to directly inject a string inside an application rather than single key presses. This is incredibly helpful for a text expander, but it's not supported by all applications. The alternative is implementing the approach used on Linux, which basically creates a lookup table of all the keys+modifiers => char, and then injects the sequence of keypresses to obtain the desired result. Besides the complexity, also this solution has a few downsides, for example you can't inject characters that are not available on the keyboard

**Comment by JamesDBartlett3** [comment]
@federico-terzi, the "Use legacy console" box is un-checked on both Windows PowerShell and PowerShell Core.
![image](https://user-images.githubusercontent.com/37491308/137037048-929990ca-1c97-400f-bcf7-1c365171a6be.png)

**Comment by smeech** [comment]
Is this still a problem with the current releases of Espanso and Powershell?

**Comment by smeech** [comment]
Happy to reopen if you wish to respond, but I realise this is an old Issue, and is probably not a problem with the current release.
