### ISSUE TITLE
Espanso behaves inconsistently with Remote desktop software

### ISSUE THREAD

**Issue by diabolic-preacher** [espanso/espanso#640]
[Workspot](https://www.workspot.com/) is a Windows desktop VM provisioned by enterprises for users to work remotely without having to connect to VPN separately.

espanso on this remote desktop (connected using workspot client), is almost unusable. just pressing Super key, keeps toggling it between disabled and enabled. 

Replacements usually either will not work. i.e. the trigger will be removed but the replacement text won't appear. or everything except last few characters would be replaced and the cursor would jump down few lines. nothing special in the replacement text except using newline character \n (for signature).

These problems don't happen on the Windows 10 installed on bare metal/laptop.

**Comment by federico-terzi** [comment]
Hey @diabolic-preacher,

I'm sorry you experienced this problem! Espanso is known to be a bit problematic when used through remote desktop tools (#378 #463 #377)

Unfortunately, there is not much I can do at the moment, as the development resources are limited right now and we need to focus on other crucial issues.
That said, thank you for raising this problem! I'll keep the issue around so that hopefully one day it will get fixed

Cheers :)

**Comment by diabolic-preacher** [comment]
Thank you for your reply. I narrowed down the problem further to :-
1. using espanso on both local and remote desktop can lead to inconsistent behavior, primarily on the remote desktop side. why it keeps getting disabled, is a suspense
2. if using a combination of espanso and any other software on local and remote desktops, one should not use the same shortcodes, as the local machine software overrides the key capturing of the software on remote desktop side software. here software refers to any text expansion software.

**Comment by federico-terzi** [comment]
@diabolic-preacher Interesting, thank you for sharing!

**Comment by jgharding** [comment]
After Googling this issue and finding this thread, I figured I'll add some more interesting details of other remote access programmes and how they behave, in case they're ever useful in future:

- **Parsec**: Parsec completely ignores Espanso. 

- **AnyDesk**: Anydesk works strangely, it does not delete the trigger word, and instead puts the replacement directly after it. as an example, woh and who will result in "woh who" from only typing woh.

For now I disable Espanso for remote work,

**Comment by AucaCoyan** [comment]
Remote Desktop is something that is outside of scope 😢 . We couldn't do it until today!

**Comment by GoodAnalysis** [comment]
Sorry to necro, also came here via google, but just a +1 on getting expanse to work on remote desktops. Parsec in particular is heavily used by our team and expanso is completely ignored by it.

**Comment by Elaws** [comment]
Hello, noticed the same problem when using Moonlight-Qt (client) & Sunshine (Host).

**Comment by Frzjck** [comment]
Had issue using Parsec - espanso did not react to triggers. Adding this line to config fixed it `win32_exclude_orphan_events: false`.

**Comment by Elaws** [comment]
> Had issue using Parsec - espanso did not react to triggers. Adding this line to config fixed it `win32_exclude_orphan_events: false`.

Tried on Moonlight Qt + Sunshine : unfortunately it doesn't work.

E.g., if I have following shortcuts :

`@jd : johndoe@mail.fr`
`:right : →`

If I type those shortcuts, instead of doing nothing (without your trick), it does this :

`@jd` generates `dddd`
`:right` generates `→:right`

So that's glitchy & unusable here.

**Comment by Elaws** [comment]
@federico-terzi : Hello, any plans to improve this, 5 years later ? Many thanks !
