### ISSUE TITLE
README.md is hard-coded with capital letters and is case sensitive

### ISSUE THREAD

**Issue by jpmvferreira** [espanso/espanso#641]
Just a tiny (very tiny) bug report, i have two repositories, one which features a package with a file named `readme.md` and the (almost) same package in a different repository with `README.md`, trying to install the first one gives `Unable to parse Package info from README.md` while the second one works.

After looking at the source code (and pretending i know rust) i got the impression that the `README.md` was hard-coded and case sensitive, and after changing all of the `readme.md` to `README.md` the package installed as expected.

**Comment by Scrumplex** [comment]
Looks okay to me. Remember that Unix-like operating systems and, by extension, file systems are also case sensitive. Same with Git IIRC. That means that you have a `readme.md` and `README.md` in the same directory at the same time. Instead of doing magic of figuring out which file to use, I would suggest to keep it case sensitive.

**Comment by JPUnD** [comment]
I know, I just mentioned this in this case because in Github having `README.md` or `readme.me` is irrelevant, so to be consistent I believe Espanso should be case insensitive, or at least have a small warning in the [documention related to package building](https://espanso.org/docs/packages/#creating-a-package).

**Comment by federico-terzi** [comment]
@JPUnD Thank you for the feedback! We are planning to completely refactor the way packages are structured, so there is a very high probability that this won't be an issue in the future.

That said, I tend to agree with @Scrumplex, I'd prefer to keep it case-sensitive (albeit with a warning as you suggested)

Cheers :)

**Comment by jpmvferreira** [comment]
I've decided to pick back up my Espanso package today and realized this has already been solved in the new refactor so I'm going to close this issue.
