### ISSUE TITLE
Fake data generator package

### ISSUE THREAD

**Issue by 4x10m** [espanso/espanso#699]
Hello, I didn't found any repository reserved to packages.
An idea has directly cross my spirit while i was discovering this awesome project and it seems that nobody thought about it before.
This idea is the abality to insert fake data with espanso.
Example: you tip :ffirstname and it insert a just generated hotly cutting edge fake human firstname.
I think i have the skills to make it by myself but not necessarily the time, btw i have opened this issue to share the idea.

Voilà. Thank you very meuch.

**Comment by es183923** [comment]
This idea can be easily implemented by using the `random` extension, or by using a `shell` script.

For example, you could add [this](https://gist.github.com/es183923/96b06eecb86cb14a0e6bf590c3a16022) following into your `default.yml` to generate a random first name. (I used a gist because it was too big for a code block.) It gets a random element from an array of size 3006.

**Comment by federico-terzi** [comment]
Hey guys,

Thank you for the feedback! I can really see how this could be useful. I'd be happy to review a community-made package for faking data (though I'll probably post-pone the review to the end of summer as I'm currently pretty busy).
I'd suggest to use the random extension as @es183923 suggested, so that we can avoid the shell altogether

Cheers :)

**Comment by es183923** [comment]
I used a shell script because it would make the code have a much smaller size, and not require 3006 lines.

**Comment by federico-terzi** [comment]
@es183923 You could also use the YAML array notation with the Random extension if you prefer to keep them in one line :)

```yaml
  - trigger: ":quote"
    replace: "{{output}}"
    vars:
      - name: output
        type: random
        params:
          choices: ["one", "two", "three"]
```

**Comment by es183923** [comment]
Ah, thanks!
