### ISSUE TITLE
Windows Edge prevents espanso from being downloaded due to missing code-signing

### ISSUE THREAD

**Issue by jeripi** [espanso/espanso#702]
Windows Edge/SmartScreen seems to think the installation file will harm my computer (this is during a download attempt, not during installation).

**Comment by federico-terzi** [comment]
Hey @jeripi,

I'm sorry you experienced this problem! Unfortunately, this is a known issue and it happens because espanso is not [code-signed](https://en.wikipedia.org/wiki/Code_signing).

I'd love to add code-signing to espanso, but the required certificates (EV Code signing certificate) is incredibly expensive (300-600 per year) and I can't really afford to spend that much on a project that doesn't bring any revenue :)

So currently, the alternatives are:
* Download the non-signed binary which will show you that warning
* Clone the repo and compile the source yourself (which is definitely not impossible, but non trivial either. I'm working to make the process easier in v2 #594 )

There are also cheaper certificates, but they still suffer from this problem, so there's not much point using them: https://security.stackexchange.com/questions/139347/smart-screen-filter-still-complains-despite-i-signed-the-executable-why

Cheers :)

**Comment by CountCypher** [comment]
I'm facing the same issue, that Edge's Smart Screen prevents download of the installer exe file. 
Just a wild guess from a non-developer: If code signing certificate is too expensive (which I understand), could submitting the file here maybe prevent it from being flagged as malware?
https://www.microsoft.com/en-us/wdsi/filesubmission/
