### ISSUE TITLE
espanso's default file keeps on resetting.

### ISSUE THREAD

**Issue by al-lad** [espanso/espanso#705]
Context : I have my espanso default.yml file synced between my computers. Some of my computers seem to have two instances of espanso running at the same time.

Regularly I realize the default file has been rewritten to its default state by one of my computers, deleting all of my custom triggers. Any idea what could be happening ?

**Comment by federico-terzi** [comment]
Hey @al-lad,

I'm sorry you experienced this problem!

> Context : I have my espanso default.yml file synced between my computers. Some of my computers seem to have two instances of espanso running at the same time.

This is nothing to worry about, it's the expected behavior. Espanso currently uses 2 processes to work, one is the "deamon" and the other is the "worker".

> Regularly I realize the default file has been rewritten to its default state by one of my computers, deleting all of my custom triggers. Any idea what could be happening ?

This is strange, perhaps there is a race condition somewhere in the process. What do you use to sync your configs?

Also, given that version 2 (#594) will come with a brand new implementation, there is a very good chance that problem will go away :)

Cheers :)

**Comment by al-lad** [comment]
Thanks for your reply. 
For now I've tried putting my triggers in a different .yml file in the user folder. We'll see if that stays.

> What do you use to sync your configs?
I'm using Mega sync.

**Comment by federico-terzi** [comment]
Interesting, thank you. Let me know if you discover something new :)

**Comment by jpetazzo** [comment]
For what it's worth, I experienced something similar - Espanso was rewriting my configuration files and offering me to run the migration agent at each restart, ... until I realized that I had two different versions of Espanso running on two different computers (with the configuration folder sync'd over Dropbox). And of course to make things more interesting, it didn't happen all the time; only when the 2nd computer was on (which was rare because it's an older computer that I only boot once in a while) 🙃

So if you're experiencing similar issues (configuration being re-created mysteriously, Espanso restarting mysteriously because "configuration has changed"...) check that you don't have another instance running on another computer. 😅
