### ISSUE TITLE
Panic on null byte Macos; not Windows

### ISSUE THREAD

**Issue by pocc** [espanso/espanso#834]
espanso panics whenever null bytes are involved. This is either due to a null byte in `replace` or a null byte that is being returned as output from a shell script. You can test this with a bash script consisting of `printf '\x00'`.

Macos: 11.6
Espanso installed via brew: 0.7.3

```
matches:
  - trigger: ";testnull"
    replace: "\x00"
```

Which triggers this in `espanso log`

```
17:29:25 [ERROR] thread 'daemon_background' panicked at 'nul byte found in provided data at position: 0': src/keyboard/macos.rs:35
stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: log_panics::init::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: std::panicking::begin_panic
   7: espanso::engine::Engine<S,C,M,U,R>::inject_text
   8: espanso::engine::Engine<S,C,M,U,R>::inject_match
   9: espanso::matcher::<impl espanso::event::KeyEventReceiver for M>::on_key_event
  10: <espanso::event::manager::DefaultEventManager as espanso::event::manager::EventManager>::eventloop
  11: espanso::worker_background
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
  13: core::ops::function::FnOnce::call_once{{vtable.shim}}
  14: std::sys::unix::thread::Thread::new::thread_start
  15: _pthread_start
```

I've checked on Windows to see if the behavior manifests there and it does not. Instead of `printf '\x00'`, I used `$bytes [Byte[]] (0x00); $bytes`.

**Comment by federico-terzi** [comment]
Hey @pocc,

Thanks for reporting this issue! May I ask you what is your use case to include null-bytes in replacements? :)

Cheers :)

**Comment by pocc** [comment]
There is a company cli program that I use to gather data and all of the data it returns start with a null byte for some reason.

**Comment by federico-terzi** [comment]
@pocc All right, thank you! I'll investigate

**Comment by pocc** [comment]
Thanks for your interest - I appreciate it! This is a great project and there's so much it can do, but also so much more potential.

I wouldn't mark this as high priority because it's easy to mitigate in scripts by removing the null byte in bash with `tr -d '\000'` or python byte replacement.

Is there any way to make it so that errors get printed as replacement text instead of there being a NOOP? It would make troubleshooting scripts easier to iterate.

**Comment by federico-terzi** [comment]
> Is there any way to make it so that errors get printed as replacement text instead of there being a NOOP? It would make troubleshooting scripts easier to iterate.

That's a very good point! I've implemented something similar yesterday, see: https://github.com/federico-terzi/espanso/issues/774#issuecomment-955794350 which will be shipped in the next v2.0.5-alpha release.

The idea would be to say "an error occurred, view the logs" after a replacement fails, and on top of that, make it easier to view the logs afterward.

>Is there any way to make it so that errors get printed as replacement text 

I decided against replacing the match with the whole error because it might happen that those errors become multiline replacements, which might be problematic in some circumstances. For example:

* You are inside a terminal
* You launch an Espanso's replacement
* It fails, replacing with the (multiline) error message
* This in turn causes multiple (nonsense) commands to be executed, because each newline is considered a command

For this reason, it just prints a (single line) error message, and then you should check out the logs (there will probably be a dedicated window for that)

Cheers :)

**Comment by pocc** [comment]
Sounds like a great solution. Can't wait for v2 to go mainstream!

**Comment by smeech** [comment]
Is this still a problem with the current release? I'll close it for now, but am happy to reopen if necessary.
