### ISSUE TITLE
Expand M1 support to be Universal App support

### ISSUE THREAD

**Issue by WardsParadox** [espanso/espanso#843]
#619  added M1 support to the upcoming release, but could this be made to make the app universal? That way it could be 1 build, no matter what arch for Mac :) 

Found this on stack overflow that seems like it should work (I'm pulling down the repo to test)

DKROOT=$(xcrun -sdk macosx11.1 --show-sdk-path) \
MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx11.1 --show-sdk-platform-version) \
cargo build --target=aarch64-apple-darwin

**Comment by federico-terzi** [comment]
Hey @WardsParadox,

Thank you for the feedback! I've played with the Universal Bundle idea for a while and I decided against it (for now) because I'd like Espanso to stay lean in size (currently at ~17mb).
In fact, there is a script to create the universal binary already, but I still need to evaluate pros and cons: https://github.com/federico-terzi/espanso/blob/master/Makefile.toml#L67

Cheers :)
