### ISSUE TITLE
+ (Plus) stripped during config file migration

### ISSUE THREAD

**Issue by tiktuk** [espanso/espanso#853]
Hi again,

I just ran the legacy to 2.0 config migration tool and noticed that plusses were stripped from replacements with international phone numbers (eg. `+1020304050` became `1020304050`).

Running espanso 2.0.4-alpha.

As always, thanks for the great work :) .

**Comment by federico-terzi** [comment]
Hey @tiktuk,

I'm sorry you experienced this problem! Could you please post an example of YAML that was corrupted?

I suspect this is because the first YAML was interpreted as a number and when it was re-encoded after the migration, the + was stripped off. In theory, having the double quotes around the number should prevent this, but it's strange anyway :)

Cheers :)

**Comment by tiktuk** [comment]
> I'm sorry you experienced this problem! Could you please post an example of YAML that was corrupted?

No worries and sure,

      - trigger: ":tdp"
        replace: +4720304050

became

      - trigger: ":tdp"
        replace: 4720304050

for instance.

> I suspect this is because the first YAML was interpreted as a number and when it was re-encoded after the migration, the + was stripped off. In theory, having the double quotes around the number should prevent this, but it's strange anyway :)

That sounds like a likely reason, yes :) .

**Comment by smeech** [comment]
I'll close this for now, but if the problem persists with the current version of Espanso, we can reopen it.
