### ISSUE TITLE
Improve initial Wayland window appearance

### ISSUE THREAD

**Issue by federico-terzi** [espanso/espanso#976]
Espanso currently needs to spawn a small window when starting on Wayland to gather the necessary information about the active keyboard. Currently, the window contains a rainbow, but some users reported it being annoying.
Investigate if we can make it full black or with an espanso logo.

**Comment by nnuel** [comment]
Most likely I can detect the window in wayland, and make it a floating one, instead of a tiled one. Or maybe as an unfocused window on another workspace. These are all solutions on the user end of course, and not within the program. 

Would there be other ways of putting the active keyboard in a .config, so it doesn't have to do the automatic check?

That last one might be neater solution, or have it get it automatic once and then store it as a default for later.

**Comment by federico-terzi** [comment]
@nnuel Thank you for the feedback!

> Would there be other ways of putting the active keyboard in a .config, so it doesn't have to do the automatic check?

Unfortunately, it's not that simple... The window also detects the current keyboard _state_, such as which modifiers are pressed and which not, so we can't hard-code them into the config :(

**Comment by AucaCoyan** [comment]
later duplicated in #1776 and fixed by #1901
